runtime: nodejs16 # or another supported version

instance_class: F2

env_variables:
  POSTGRES_HOST: /cloudsql/hlth-run-app:asia-south1:hlthrunapp
  INSTANCE_CONNECTION_NAME: hlth-run-app:asia-south1:hlthrunapp
  # POSTGRES_HOST: /cloudsql/hlth-run-app-prod:asia-south1:hlth-run-app-prod
  # INSTANCE_CONNECTION_NAME: hlth-run-app-prod:asia-south1:hlth-run-app-prod
  PORT: 8080

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
